export const SET_LANGUAGE = "SET_LANGUAGE";

export const PROPERTIES = {
  LOAD: "PROPERTIES_LOAD",
  LOAD_SUCCESS: "PROPERTIES_LOAD_SUCCESS",
  LOAD_FAIL: "PROPERTIES_LOAD_FAIL",
  LOAD_PROPERTIES_TYPES: "LOAD_PROPERTIES_TYPES",
};
